kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "chaos-mesh-manager-role"
rules:
  - apiGroups: [ "" ]
    resources: ["pods", "namespaces"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [ "chaos-mesh.org" ]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
